94 admininteresting facts block create interesting facts
project-studying-dotnet/Streetcode-Server-September pull request #110
Opened 2024-09-13 18:32 UTC by refokcer

dev
## Summary of issue

Create endpoint.
Create CreateFactHandler and CreateFactCommand.
Cover with unit tests.

## Summary of change

Made endpoint for Fact / Create.

Fixed FactDto betray StreetcodeId as it is a mandatory parameter in the database. 
Also in FactEntety StreetcodeId became with attribute “required”.

Made mediatr for processing the creation of Fact with a little logic.

The mediatrist is covered with unit tests
Also tested with Swagger

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=50%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  PR meets all conventions

2024-09-14 08:56 UTC, jimmy2jk requested changes
- Create appropriate `CreateFactDto` (or something similar) for this action.
- `CreateFactDto` must not contain `Id` of fact.
- Also `CreateFactDto` should have nullable `ImageId` property to remove redundant check in `CreateFactHandler`.
- Configure mapping for new Dto.

2024-09-14 08:56 UTC, jimmy2jk commented on Streetcode/Streetcode.BLL/Dto/Streetcode/TextContent/Fact/FactDto.cs
> +    public int StreetcodeId { get; set; }
This property is unnecessary for purpose of this Dto

2024-09-14 08:56 UTC, jimmy2jk commented on Streetcode/Streetcode.BLL/MediatR/Streetcode/Fact/Create/CreateFactHandler.cs
> +            if (newFact.ImageId == 0)
This check can be removed by making ImageId nullable in CreateFactDto.

2024-09-14 16:21 UTC, MishaHMK approved these changes

2024-09-15 13:56 UTC, jimmy2jk approved these changes

2024-09-15 13:57 UTC, merged