Delete source block
project-studying-dotnet/Streetcode-Server-September pull request #113
Opened 2024-09-14 16:25 UTC by MishaHMK

dev

## Summary of issue

[Issue](https://github.com/orgs/project-studying-dotnet/projects/15/views/1?pane=issue&itemId=79455193)

## Summary of work

Streetcode/Streetcode.BLL/Exceptions/ - CustomException class (type for custom exceptions)
Streetcode.WebApi/Extensions/ - GlobalExceptionHanderBuilderExtension (to register middleware, used in Program.cs)
Streetcode.WebApi/ - GlobalExceptionHandlingMidlleware (middleware to hadle all exceptions)

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=50%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  PR meets all conventions

2024-09-14 17:26 UTC, jimmy2jk requested changes

2024-09-14 17:26 UTC, jimmy2jk commented on Streetcode/Streetcode.XUnitTest/MediatRTests/Sources/SourceLinkCategory/DeleteCategotyHandlerTests.cs
> +        public async Task Handle_ReturnsSuccess_WhenCategoryNotFound()
Test for failure result () named `..._ReturnsSuccess_...`

2024-09-14 17:26 UTC, jimmy2jk commented on Streetcode/Streetcode.XUnitTest/MediatRTests/Sources/SourceLinkCategory/DeleteCategotyHandlerTests.cs
> +    public class DeleteCategotyHandlerTests
Typo 'CategoTy'.

2024-09-14 17:26 UTC, jimmy2jk commented on Streetcode/Streetcode.BLL/MediatR/Sources/SourceLinkCategory/Delete/DeleteCategoryHandler.cs
> +                return Result.Ok(srcCategoryDto);
Why do you need to return Dto deleted item?

2024-09-14 21:34 UTC, jimmy2jk requested changes

2024-09-14 21:34 UTC, jimmy2jk commented on Streetcode/Streetcode.XUnitTest/MediatRTests/Sources/SourceLinkCategory/DeleteCategoryContentByStreetcodeIdHandlerTests.cs
> +            _repositoryMock.Verify(r => r.SaveChangesAsync(), Times.Once);
Verify call of Delete method. Not SaveChangesAsync

2024-09-14 21:43 UTC, jimmy2jk approved these changes
Great Job👍👍👍

2024-09-15 14:10 UTC, refokcer approved these changes

2024-09-15 14:11 UTC, merged