setup identity
project-studying-dotnet/Streetcode-Server-September pull request #173
Opened 2024-09-21 12:55 UTC by GrinchArt

dev
## Summary of issue

ToDo

## Summary of change

ToDo

## Comments

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=50%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  PR meets all conventions

2024-09-21 14:09 UTC, jimmy2jk requested changes
Impossible to apply migrations. Neither on project startup, running `dotnet ef database update` in console nor deleting and recreating database from zero work correctly. Entire application crashes.

2024-09-21 14:09 UTC, jimmy2jk commented on Streetcode/Streetcode.WebApi/Program.cs
> +builder.Services.AddIdentity<User, IdentityRole<int>>()
Extra services should not be registered directly in `Program.cs`. Move this into `Streetcode.WebApi.Extensions.ServiceCollectionExtesions`. Either in `AddApplicationServices` or custom helper method similar to `AddModelValidationService`.

2024-09-21 14:20 UTC, jimmy2jk commented on Streetcode/Streetcode.DAL/Entities/Users/User.cs
>          public string Password { get; set; } = null!;
Try to change to `PasswordHash` from `IdentityUser`

2024-09-21 18:13 UTC, MishaHMK commented
> Impossible to apply migrations. Neither on project startup, running `dotnet ef database update` in the console nor deleting and recreating the database from zero work correctly—the entire application crashes.

Same 

1. You should override properties inherited from the class. Read warnings for props in User and DbContext
2. Register services in 'WebApi/Extensions/ServiceCollectionExtensios', not in 'Program.cs'
3. DbContext is already registered in this application
4. Tables from your migration do not create, after 'Update-Database' command, therefore app doesn't run

2024-09-21 18:14 UTC, MishaHMK requested changes
1. You should explicitly write properties inherited from the Identity class. Read warnings for props in User and DbContext
2. Register services in 'WebApi/Extensions/ServiceCollectionExtensios', not in 'Program.cs'
3. DbContext is already registered in this application
4. Tables from your migration do not create, after 'Update-Database' command, therefore app doesn't run

2024-09-21 18:25 UTC, jimmy2jk commented
Potential issue in absence of `UserName` attribute in User (renamed to AspNetUsers) table. Seems like migration doesn't finish succesfully, changes are not applied at all. And while seeding DB app tries to execute query to non-existing tables

2024-09-23 15:20 UTC, jimmy2jk approved these changes

2024-09-23 18:18 UTC, MishaHMK approved these changes

2024-09-23 18:18 UTC, merged