Endpoint register
project-studying-dotnet/Streetcode-Server-September pull request #189
Opened 2024-09-24 17:42 UTC by GrinchArt

dev
## Summary of issue

ToDo

## Summary of change

ToDo

## Comments

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=50%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  PR meets all conventions

2024-09-24 21:32 UTC, MishaHMK approved these changes

2024-09-25 05:59 UTC, jimmy2jk requested changes
Fix issues described in comments bellow. 
Also this task also dhould be covered with unit tests at least 50%

2024-09-25 05:59 UTC, jimmy2jk commented on Streetcode/Streetcode.BLL/MediatR/Users/Register/RegisterUserCommandHandler.cs
> +                Role = "User"
You pass user role in register dto but all registered user will be with role "User". Something of this dhould be removed. Either ROle property in Dto or this assignment of string.
Also it's better to have Enum or a set ot const strings globaly in program and use them everywhere you need

2024-09-25 05:59 UTC, jimmy2jk commented on Streetcode/Streetcode.BLL/MediatR/Users/Register/RegisterUserCommandHandler.cs
> +            await _userManager.AddToRoleAsync(user, "User");
You check if the role, passed in dto, exists in Db, add this role if it doesn't exist, and then do nothing with it?
You just add created user to default role "User".

2024-09-25 05:59 UTC, jimmy2jk commented on Streetcode/Streetcode.BLL/MediatR/Users/Register/RegisterUserCommandHandler.cs
> +            var result = await _userManager.CreateAsync(user, userDto.Password);
Password here is not hashed. We can not store pure passwords. It always should be hashed!
Impelement service for hashing

2024-09-25 10:20 UTC, GrinchArt commented on Streetcode/Streetcode.BLL/MediatR/Users/Register/RegisterUserCommandHandler.cs
> +            await _userManager.AddToRoleAsync(user, "User");
fixed the issue with roles

2024-09-25 10:20 UTC, GrinchArt commented on Streetcode/Streetcode.BLL/MediatR/Users/Register/RegisterUserCommandHandler.cs
> +                Role = "User"
Fixed using UserRole enum

2024-09-26 10:43 UTC, jimmy2jk commented on Streetcode/Streetcode.BLL/MediatR/Users/Register/RegisterUserCommandHandler.cs
> +            };
This should be done witn AutoMapper

2024-09-26 10:43 UTC, jimmy2jk commented on Streetcode/Streetcode.BLL/MediatR/Users/Register/RegisterUserCommandHandler.cs
> +            };
This should be done with AutoMapper

2024-09-26 10:44 UTC, jimmy2jk approved these changes

2024-09-26 10:45 UTC, jimmy2jk reviewed
Handler and AutoMapper (currently is not used, but should be) must be covered with unit tests!

2024-09-26 11:43 UTC, GrinchArt reviewed
Added Automapper, plus unit tests with the last push

2024-09-26 11:43 UTC, GrinchArt commented on Streetcode/Streetcode.BLL/MediatR/Users/Register/RegisterUserCommandHandler.cs
> +            };
Added Automapper, plus unit tests

2024-09-26 11:43 UTC, GrinchArt commented on Streetcode/Streetcode.BLL/MediatR/Users/Register/RegisterUserCommandHandler.cs
> +            };
Added Automapper, plus unit tests

2024-09-26 11:53 UTC, jimmy2jk approved these changes

2024-09-26 11:53 UTC, jimmy2jk commented on Streetcode/Streetcode.BLL/Mapping/Users/UserProfile.cs
> +               .ForMember(dest => dest.Role, opt => opt.Ignore());
Fix this mapping as suggested below to avoid extra assigning in Handler:
`CreateMap<RegisterUserDto, User>().ForMember(dest => dest.Role, opt => opt.MapFrom(src => src.Role.ToString()));`

2024-09-26 11:53 UTC, jimmy2jk commented on Streetcode/Streetcode.BLL/MediatR/Users/Register/RegisterUserCommandHandler.cs
> +            user.Role = userDto.Role.ToString();
redundant assignment that can be done by mapper.

2024-09-26 11:53 UTC, jimmy2jk commented on Streetcode/Streetcode.BLL/Mapping/Users/UserProfile.cs
> +            CreateMap<User, UserDto>()
Same here:
`CreateMap<User, UserDto>().ForMember(dest => dest.Role, opt => opt.MapFrom(src => Enum.Parse<UserRole>(src.Role)))`

2024-09-26 11:53 UTC, jimmy2jk commented on Streetcode/Streetcode.BLL/MediatR/Users/Register/RegisterUserCommandHandler.cs
> +            createdUserDto.Role = Enum.Parse<UserRole>(user.Role);
redundant assignment that can be done by mapper.

2024-09-26 12:04 UTC, GrinchArt commented on Streetcode/Streetcode.BLL/Mapping/Users/UserProfile.cs
> +               .ForMember(dest => dest.Role, opt => opt.Ignore());
fixed

2024-09-26 12:04 UTC, GrinchArt commented on Streetcode/Streetcode.BLL/Mapping/Users/UserProfile.cs
> +            CreateMap<User, UserDto>()
fixed

2024-09-26 12:06 UTC, GrinchArt commented on Streetcode/Streetcode.BLL/MediatR/Users/Register/RegisterUserCommandHandler.cs
> +            user.Role = userDto.Role.ToString();
removed

2024-09-26 12:06 UTC, GrinchArt commented on Streetcode/Streetcode.BLL/MediatR/Users/Register/RegisterUserCommandHandler.cs
> +            createdUserDto.Role = Enum.Parse<UserRole>(user.Role);
removed

2024-09-30 17:52 UTC, merged