getommentswithreplies and unit tests
project-studying-dotnet/Streetcode-Server-September pull request #218
Opened 2024-09-26 14:00 UTC by GrinchArt

dev
## Summary of issue

ToDo

## Summary of change

ToDo

## Comments

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=50%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  PR meets all conventions

2024-09-26 15:22 UTC, jimmy2jk requested changes
Migration fails. In one of recent PRs `ParentCommentId` field for Comment have already been created. Pull changes and update your local DB.

2024-09-26 15:22 UTC, jimmy2jk commented on Streetcode/Streetcode.DAL/Persistence/Migrations/20240926125633_Comment entity changes.cs
> +                nullable: true);
This field already exists in DB. Migration fails.

2024-09-27 13:32 UTC, GrinchArt commented on Streetcode/Streetcode.DAL/Persistence/Migrations/20240926125633_Comment entity changes.cs
> +                nullable: true);
done

2024-09-27 13:32 UTC, GrinchArt commented on Streetcode/Streetcode.WebApi/Controllers/Streetcode/TextContent/CommentController.cs
> +        return BadRequest(result.Errors);
done

2024-09-27 17:51 UTC, jimmy2jk requested changes

2024-09-27 17:51 UTC, jimmy2jk commented on Streetcode/Streetcode.BLL/Dto/Streetcode/TextContent/Comment/CommentWithRepliesDto.cs
> +        public int? ParentCommentId { get; set; }
All of this are fields that you inherit from `CommentDto`. Either remove them or remove inheritance from `CommentDto`.

_Note: I'm not sure wether inheritance for Dto is a good idea. If change parrentDto, it will affect on child Dto, and we rarely need this complexity. So maybe indeed removing inheritance the only correct solution here._

2024-09-27 17:51 UTC, jimmy2jk commented on Streetcode/Streetcode.BLL/Mapping/Streetcode/TextContent/CommentProfile.cs
> +            .ReverseMap();
Not an issue to fix necessarily, but take into account. Explicit mapping configuration with `ForMember` is not needed here. `ParentCommentId` here:
- is it's own field of entity and dto (not a field of internal object), 
- has the same name,
- has the same data type.
So it is enough to use `CreateMap<Comment, CommentDto>().ReverseMap();` here. AutoMapper will do everything by itself.

2024-09-29 09:26 UTC, GrinchArt commented on Streetcode/Streetcode.BLL/Dto/Streetcode/TextContent/Comment/CommentWithRepliesDto.cs
> +        public int? ParentCommentId { get; set; }
Initially, I had the idea to make the inheritance work, but then when calling the swagger, I faced a situation of “chaotic” display of information, which is why I decided to actually add fields to display them correctly.

Therefore, I removed the inheritance in the last change

2024-09-29 09:27 UTC, GrinchArt commented on Streetcode/Streetcode.BLL/Mapping/Streetcode/TextContent/CommentProfile.cs
> +            .ReverseMap();
Fixed in the last change

2024-09-29 19:10 UTC, jimmy2jk approved these changes
Fix conflicts with dev and all good!

2024-09-30 07:49 UTC, MishaHMK approved these changes

2024-09-30 15:09 UTC, merged