Move jwt/login to microservice
project-studying-dotnet/Streetcode-Server-September pull request #225
Opened 2024-09-27 22:13 UTC by MishaHMK

##SUMMARY
Reused code from [my previous pr](https://github.com/project-studying-dotnet/Streetcode-Server-September/pull/182/files#diff-bb0d97b7e937337f22e15f23e49a48691869e39ae6baab7cfcf66de048f8ea9e), with some minor changes (validator doesn't have a lot of elements of main API)

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=50%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  PR meets all conventions

2024-09-29 06:32 UTC, jimmy2jk requested changes
Fix order of SeedData and ApplyMigrations. Also little changes to formatting required

2024-09-29 06:32 UTC, jimmy2jk commented on Streetcode/Streedcode.Identity/Program.cs
>  await app.ApplyMigrations();
SeedDataAsync must be called adter ApplyMigrations

2024-09-29 06:32 UTC, jimmy2jk commented on Streetcode/Streedcode.Identity/Services/Realizations/JwtService.cs
> +            };
Fix formatting. Opening curly braces should be pleced on a new line.

2024-09-29 06:32 UTC, jimmy2jk commented on Streetcode/Streedcode.Identity/Services/Realizations/JwtService.cs
> +                   throw new InvalidOperationException("Token generation failed"); ;
one extra `;`

2024-09-29 16:09 UTC, jimmy2jk approved these changes

2024-09-30 17:40 UTC, KarmazinN approved these changes

2024-10-01 08:45 UTC, merged