RelatedTermHandler UnitTests
project-studying-dotnet/Streetcode-Server-September pull request #23
Opened 2024-09-05 15:35 UTC by MishaHMK

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2024-09-05 16:29 UTC, refokcer requested changes
Handle_ReturnsError_WhenMappingToDtoFailed
тести на логіку саме медіатора, тут не має міститися тестування роботи маппера

2024-09-05 16:33 UTC, refokcer reviewed
Так само і WhenSaveFailed, це не логіка медіатора
Зберижи поки окремо, на міті завтра точно спросимо, але в теоріі це тести не до логіки маппера

2024-09-05 16:43 UTC, refokcer reviewed
Вже спитав на всяк випадок у чаті

2024-09-05 17:01 UTC, refokcer approved these changes
Окей, аппрувнул

2024-09-06 16:49 UTC, KarmazinN approved these changes

2024-09-06 16:50 UTC, merged