fix/14/ enable server certificate validation
project-studying-dotnet/Streetcode-Server-September pull request #25
Opened 2024-09-05 19:22 UTC by jimmy2jk

dev
## GitHub Project

* [GitHub Board Ticket](https://github.com/project-studying-dotnet/Streetcode-Server-September/issues/14)

## Code reviewers

- [ ] @refokcer 
- [ ] @GrinchArt 

## Summary of issue

Server certificate validation was disabled by defining custom callback function that always returns true. This means that all SSL certificates will be accepted, even if they are invalid, expired, or self-signed. This expose app to man-in-the-middle attacks and other vulnerabilities.

## Summary of change

Remove custom callback function and rely on default validation implementation by Microsoft. This is also recomended by SonarCloud.

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

Closes issue #14

2024-09-06 06:38 UTC, vladtymo requested changes

2024-09-06 06:38 UTC, vladtymo commented on Streetcode/Streetcode.WebApi/Utils/WebParsingUtils.cs
> -        clientHandler.ServerCertificateCustomValidationCallback = (message, cert, chain, errors) => true;
Investigate this article: https://learn.microsoft.com/ru-ru/dotnet/core/extensions/sslstream-best-practices
What does the client handler do when ServerCertificateCustomValidationCallback is not set?

2024-09-06 11:26 UTC, refokcer approved these changes

2024-09-06 16:47 UTC, GrinchArt approved these changes

2024-09-06 16:53 UTC, refokcer approved these changes

2024-09-06 18:40 UTC, jimmy2jk commented on Streetcode/Streetcode.WebApi/Utils/WebParsingUtils.cs
> -        clientHandler.ServerCertificateCustomValidationCallback = (message, cert, chain, errors) => true;
In article nothing was said about default implementation. But while trying to fix vulnerability, I found similar answear on Stack Overflow.
`ServerCertificateCustomValidationCallback` has a default implementation in `HttpClientHandler`, which ensures standard SSL certificate validation according to the system certificate store and trusted root certificates.
By default, if we don't set a custom validation callback, the system will:
- Validate that the server's SSL certificate is valid.
- Check if the certificate chain is trusted (i.e., issued by a trusted Certificate Authority).
- Ensure that the certificate hasn't expired or been revoked.
[Stack overflow question](https://stackoverflow.com/questions/57755028/how-to-validate-a-ssl-certificate-with-c-sharp)

2024-09-09 06:22 UTC, vladtymo approved these changes
Everything is good

2024-09-09 06:23 UTC, merged