276 fix sonar 20
project-studying-dotnet/Streetcode-Server-September pull request #277
Opened 2024-10-08 18:34 UTC by refokcer

dev
## Summary of issue

fix sonar issues

## Summary of change

LINQ expressions are used
Resolved some null reference possible
And annother issues 

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=50%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  PR meets all conventions

2024-10-09 16:53 UTC, jimmy2jk requested changes
Fix issues provided in comments

2024-10-09 16:53 UTC, jimmy2jk commented on Streetcode/Streetcode.BLL/MediatR/Streetcode/RelatedTerm/Update/UpdateRelatedTermHandler.cs
This entire file must be deleted along with the command and controller endpoint as they do nothing but throw an exception

2024-10-09 16:53 UTC, jimmy2jk commented on Streetcode/Streetcode.DAL/Enums/UserRole.cs
>      public enum UserRole
Sonar requires to rename this to UserRoles.
The use of plural form for enum name is allowed as this one represents a bit fields

2024-10-10 11:14 UTC, VitaKotenko approved these changes

2024-10-10 11:15 UTC, merged