test/28/ cover GetRelatedFiguresByStreetcodeIdHandler with unit tests
project-studying-dotnet/Streetcode-Server-September pull request #41
Opened 2024-09-08 19:50 UTC by jimmy2jk

dev
## GitHub Project

* [GitHub Board Ticket](https://github.com/project-studying-dotnet/Streetcode-Server-September/issues/28)

## Code reviewers

- [ ] @refokcer 
- [ ] @GrinchArt 

## Summary of issue

GetRelatedFiguresByStreetcodeIdHandler was not covered by unit tests

## Summary of change

Created unit tests for all possible outcomes for GetRelatedFiguresByStreetcodeIdHandler.Handle method:
- when no related figure ids found: **return fail result;**
- when no related figure found: **return fail result;**
- when related figures were found: **sort images by alt, return success result and mapped data;**

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

Closes issue #28

2024-09-08 21:50 UTC, refokcer requested changes
streetcodeId в 103 line не має значення 
Тест не працює

2024-09-08 22:23 UTC, refokcer commented
Usings must be after namespase ( Codesmell )

2024-09-10 20:24 UTC, refokcer approved these changes

2024-09-11 06:08 UTC, vladtymo approved these changes

2024-09-11 06:08 UTC, merged