30-Unit Tests for mediatR StreetCode/Transcations/TransactionLink
project-studying-dotnet/Streetcode-Server-September pull request #58
Opened 2024-09-09 11:28 UTC by MishaHMK

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2024-09-09 12:07 UTC, refokcer requested changes
Bad naming:
In every class for tests when AreNull ( Result is not Ok )

In class GetTransactByStreetcodeIdHandlerTests in 48 line "transactionLink.StreetcodeId" Does not affect the performance of the test. If the id does not exist, a positive result will be returned. The test does not work correctly.

In class GetTransactLinkByIdHandlerTests in 46 line the same situation.

2024-09-09 20:25 UTC, GrinchArt approved these changes

2024-09-10 07:19 UTC, jimmy2jk approved these changes

2024-09-10 07:23 UTC, refokcer approved these changes

2024-09-10 07:23 UTC, merged