refactor/84/ move ef entity configuration to separate classes
project-studying-dotnet/Streetcode-Server-September pull request #95
Opened 2024-09-11 18:54 UTC by jimmy2jk

dev

## Summary of issue
All entity configurations for EF Core were set in `StreetcodeDbContext.OnModelCreating` method. This method was large, 
unreadable and hard to maintain.

## Summary of change
Configuration for every entity was extracted into separate class `<ModelName>Configuration` that implements `IEntityTypeConfiguration` generic interface. These classes overrides interface's method `Configure` in which all configuration for specified entity is set. 
In `StreetcodeDbContext.OnModelCreating` these configurations are applied by providing configuration class instances to `modelbuilder.ApplyConfiguration` method.
Configuration classes are placed in appropriate directories inside of `Streetcode.DAL.Persistence.Configurations` and follows structure of `Streetcode.DAL.Entities` directory.

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=50%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  PR meets all conventions

This PR closes issue #84

2024-09-11 19:20 UTC, refokcer approved these changes

2024-09-12 06:25 UTC, vladtymo commented on Streetcode/Streetcode.DAL/Persistence/StreetcodeDbContext.cs
> +        modelBuilder.ApplyConfiguration(new StatisticRecordConfiguration());
Try to use ApplyConfigFromAssembly

2024-09-12 06:27 UTC, vladtymo requested changes
Investigate ApplyConfigFromAssembly performance influence

2024-09-12 16:28 UTC, jimmy2jk commented on Streetcode/Streetcode.DAL/Persistence/StreetcodeDbContext.cs
> +        modelBuilder.ApplyConfiguration(new StatisticRecordConfiguration());
In fact, ApplyConfigurationFromAssembly doesn't affect significantly on performance and is a common practice to configure big amount of entities. Multiple ApplyConfiguration calls were replaced by single ApplyConfigurationFromAssembly call.

2024-09-13 06:35 UTC, vladtymo approved these changes
Great

2024-09-13 06:46 UTC, merged